# Generated by Django 5.0.8 on 2024-12-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='ampere',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='load_type',
            field=models.CharField(choices=[('inductive', 'Inductive'), ('capacitive', 'Capacitive')], default='inductive', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='phase',
            field=models.CharField(choices=[('single', 'Single Phase'), ('three', 'Three Phase')], default='single', max_length=50),
        ),
    ]
