# Generated by Django 5.0.8 on 2024-12-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0002_remove_project_description_project_ampere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit of this component', max_digits=10, null=True),
        ),
    ]
